# Arrays

- Not a built-in Python type
- We need to import from the array module or use NumPy arrays
- Store elements of same data type (more restricted)
- More efficient for numerical computing

## using array lib

In [13]:
import array
# syntax: array(typecode, [initializer])
my_int_array = array.array('i',[1,2,3,4]) # here i stands for integer(typically 4 bytes)
print(my_int_array)

array('i', [1, 2, 3, 4])


In [2]:
my_float_array = array.array('f',[1.0,2.0,3.0,4.0]) # here f stands for float(typically 4 bytes)
print(my_float_array)

array('f', [1.0, 2.0, 3.0, 4.0])


In [3]:
my_double_array = array.array('d',[1.0,2.0,3.0,4.0]) # here d stands for double(typically 8 bytes)
print(my_double_array)

array('d', [1.0, 2.0, 3.0, 4.0])


In [4]:
my_byte_array = array.array('b',[1,2,3,4]) 
# here b stands for signed byte(-128 to 127)
print(my_byte_array)

array('b', [1, 2, 3, 4])


In [5]:
my_unsigned_byte_array = array.array('B',[1,2,3,4])
# here B stands for unsigned byte(0 to 255)
print(my_unsigned_byte_array)

array('B', [1, 2, 3, 4])


In [6]:
my_signed_long_array = array.array('l',[1,2,3,4])
# here l stands for signed long(typically 4 bytes)
print(my_signed_long_array)

array('l', [1, 2, 3, 4])


In [7]:
my_unsigned_int_array = array.array('I',[1,2,3,4])
# here I stands for unsigned int(typically 4 bytes)
print(my_unsigned_int_array)

array('I', [1, 2, 3, 4])


### Using Numpy Arrays

In [8]:
import numpy as np

my_numpy_array = np.array([1,2,3,4])
print(my_numpy_array)

[1 2 3 4]


In [11]:
numpy_float_array = np.array([1.0,2.0,3.0,4.0], dtype=np.float32) # here we can specify the data type as well
print(numpy_float_array)

'''
But its not necessary to specify the data type as numpy will automatically 
infer it based on the input data.
'''
simple_numpy_array = np.array([1,2,3,4])
print(simple_numpy_array)

#we can check the data type of the array using the dtype attribute
print(simple_numpy_array.dtype)

[1. 2. 3. 4.]
[1 2 3 4]
int32


## Array operations

In [14]:
# append() method is used to add elements to the end of the array
simple_numpy_array = np.append(simple_numpy_array, 5)
print(simple_numpy_array)

my_int_array.append(5)
print(my_int_array)

[1 2 3 4 5 5]
array('i', [1, 2, 3, 4, 5])


In [20]:
# insert() method is used to add elements at a specific index in the array
# syntax: np.insert(arr, index, value)
simple_numpy_array = np.insert(simple_numpy_array, 0, 0) 
print(simple_numpy_array)

# insert operation is idompotent ?
# No , if we insert the same value at the same index multiple times, 
# it will be inserted multiple times in the array.

[0 0 0 0 0 0 1 2 3 4 5 5]


In [23]:
# pop() method is used to remove and returns elements from any index in the array
# by default it removes the last element if no index is specified
popped_element = my_int_array.pop()
print(popped_element)
print(my_int_array)


4
array('i', [1, 2, 3])


In [30]:
# But numpy does not have a pop() method, we can use np.delete() method to remove 
# elements from the array
np_popped_element= np.delete(simple_numpy_array, -2) # here -1 is the index of the last element
print(np_popped_element)


[0 0 0 0 0 0 1 2 3 4 5]


In [ ]:
elements = np.delete(simple_numpy_array, [0,1]) # here we are deleting the first two
# elements of the array
print(elements)

# Is delete operation idempotent ?
# No, if we delete the same index multiple times, it will delete the element at 
# that index multiple times and will return the same result each time.

[0 0 0 0 1 2 3 4 5 5]



### Key Point:

`np.delete()`, `np.append()`,` np.insert()` , `np.flip` all return NEW arrays

>> They don't modify the original. We must reassign to see changes: `arr = np.delete(arr, index)`


In [38]:
# remove() method is used to remove the first occurrence of a value from the array
my_float_array.remove(2)
print(my_int_array)

"""
If the value is not present in the array, it will raise a ValueError.
"""

array('i', [1, 3])


In [40]:
# reverse() method is used to reverse the elements of the array
my_int_array.reverse()
print(my_int_array)

# if using numpy array we can use np.flip() method to reverse the elements 
# of the array
np_flipped_array=np.flip(simple_numpy_array)
print(np_flipped_array)

array('i', [1, 3])
[5 5 4 3 2 1 0 0 0 0 0 0]


In [44]:
# sort() method is used to sort the elements of the array in ascending order
np_sorted_array = np.sort(simple_numpy_array)
print(np_sorted_array)

# using array module we can use sorted() function to sort the elements of the array
# we need to create a new array using the sorted() function as it returns a list
my_double_array = array.array('d', sorted(my_double_array))
print(my_double_array)

[0 0 0 0 0 0 1 2 3 4 5 5]
array('d', [1.0, 2.0, 3.0, 4.0])


In [48]:
# count() method is used to count the number of occurrences of a value in the array
count_of_2 = my_double_array.count(2.0)
print(count_of_2)


1


In [55]:
# extend() method is used to add elements from another array to the end of the array
my_int_array.extend([6,7,8])
print(my_int_array)

np.concatenate((simple_numpy_array, [5,6,7,8]))
print(np.concatenate((simple_numpy_array, [5,6,7,8])))

array('i', [1, 3, 6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8])
[0 0 0 0 0 0 1 2 3 4 5 5 5 6 7 8]


In [ ]:
# delete all elements from the array
# we can use del keyword to delete all elements from the array by
# specifying the slice of the entire array
# syntax: del array_name[:]

del my_int_array[:]
print(my_int_array)



array('i')


# Interview Questions

In [58]:
#1) Find second largest element in the array

def find_second_largest(arr):
    if len(arr) < 2:
        return None
    first_largest = second_largest = float('-inf')
    for num in arr:
        if num > first_largest:
            second_largest = first_largest
            first_largest = num
        elif first_largest > num > second_largest:
            second_largest = num
    return second_largest
my_array = [3, 1, 4, 1, 5, 9]
second_largest = find_second_largest(my_array)
print("Second largest element:", second_largest)




Second largest element: 5


In [ ]:
# using sorted() to find 3rd largest

arr = [3, 1, 4, 1, 5, 9]
sorted_arr= sorted(arr, reverse=True)
print(sorted_arr[2])

4


In [61]:
#1) Find second largest element in the array

def find_second_largest(arr):
    if len(arr) < 2:
        return None
    first_largest = second_largest = float('inf')
    for num in arr:
        if num < first_largest:
            second_largest = first_largest
            first_largest = num
        elif first_largest < num < second_largest:
            second_largest = num
    return second_largest
my_array = [3, 1, 4, 1, 5, 9]
second_largest = find_second_largest(my_array)
print("Second largest element:", second_largest)




Second largest element: 3


In [63]:
# reverse an array

arr = [12,34,45,22,66,67]
arr.reverse()
print(arr)


[67, 66, 22, 45, 34, 12]
